# Prediction As Classification
Continuing the 2800-HK price prediction from classification perspective

## Step 1: Import Modules and load raw data

In [92]:
#Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import itertools
import keras

In [93]:
#Import sklearn
from sklearn.preprocessing import scale

In [94]:
#Import Keras module
from keras import optimizers
from keras.models import Sequential
from keras.layers import *
from keras.utils.np_utils import to_categorical
from keras.callbacks import ModelCheckpoint, EarlyStopping

In [95]:
#pretty plots
%matplotlib inline

In [96]:
#Import price data
#Load the historical prices of 2800-HK, with lags 1 to lag 20
price_hist_data = pd.read_csv('price_only.csv', skiprows=1, parse_dates=['Date']).set_index(['Date'])
price_hist_data.head()

P   P_L1   P_L2   P_L3   P_L4   P_L5   P_L6   P_L7   P_L8  \
Date                                                                        
2007-08-31  24.35  23.80  23.35  23.70  23.90  23.30  23.35  22.70  22.05   
2007-09-03  24.30  24.35  23.80  23.35  23.70  23.90  23.30  23.35  22.70   
2007-09-04  24.30  24.30  24.35  23.80  23.35  23.70  23.90  23.30  23.35   
2007-09-05  24.35  24.30  24.30  24.35  23.80  23.35  23.70  23.90  23.30   
2007-09-06  24.50  24.35  24.30  24.30  24.35  23.80  23.35  23.70  23.90   

             P_L9  ...    P_L11  P_L12  P_L13  P_L14  P_L15  P_L16  P_L17  \
Date               ...                                                      
2007-08-31  21.85  ...    20.95  21.70  22.35  22.30  22.05  22.70  22.85   
2007-09-03  22.05  ...    20.80  20.95  21.70  22.35  22.30  22.05  22.70   
2007-09-04  22.70  ...    21.85  20.80  20.95  21.70  22.35  22.30  22.05   
2007-09-05  23.35  ...    22.05  21.85  20.80  20.95  21.70  22.35  22.30   
2007-09-06  23.30  ...    22.70  22.05  21.85  20.80  20.95  21.70  22.35   

            P_L18  P_L19  P_L20  
Date                             
2007-08-31  22.15  22.25  22.85  
2007-09-03  22.85  22.15  22.25  
2007-09-04  22.70  22.85  22.15  
2007-09-05  22.05  22.70  22.85  
2007-09-06  22.30  22.05  22.70  

[5 rows x 21 columns]

In [97]:
#Import Fundamentals Data
fund_data = pd.read_csv('new_index_data.csv', skiprows=1, parse_dates=['Date']).set_index(['Date'])
fund_data.head() 

Close   High    Low    Ask    Bid   20D Vol    MA5       MA15  \
Date                                                                        
2007-08-31  24.35  24.35  24.35  24.35  24.35  2.367823  23.82  22.841667   
2007-09-03  24.30  24.30  24.30  24.30  24.30  2.266743  23.90  23.120832   
2007-09-04  24.30  24.30  24.30  24.30  24.30  2.259649  24.02  23.412500   
2007-09-05  24.35  24.35  24.35  24.35  24.35  2.172140  24.22  23.620832   
2007-09-06  24.50  24.50  24.50  24.50  24.50  2.160638  24.36  23.825000   

                 MA12     MA20    ...        DY_LTM    DY_NTM    ADV_VOL  \
Date                              ...                                      
2007-08-31  22.696667  22.6225    ...      2.782797  2.880128  99.419898   
2007-09-03  22.830000  22.7250    ...      2.784563  2.892308  11.570023   
2007-09-04  22.960000  22.8325    ...      2.784339  2.894377  69.555725   
2007-09-05  23.136667  22.9075    ...      2.767348  2.867314  24.265623   
2007-09-06  23.373333  22.9975    ...      2.775339  2.878880  88.845002   

               PAYOUT  ANALYST_SENTIMENT  EPS_GRW_FY1  EPS_GRW_FY2     PE_NTM  \
Date                                                                            
2007-08-31  48.051962           1.909071    30.724490     2.717280  16.695058   
2007-09-03  48.305678           1.835359    31.005439     1.876752  16.709085   
2007-09-04  48.307102           1.725886    31.040968     1.891823  16.697662   
2007-09-05  48.267351           1.741908    30.716929     1.878484  16.841225   
2007-09-06  48.288397           1.696151    31.336520     1.861943  16.780660   

               PE_LTM    C2D_LTM  
Date                              
2007-08-31  16.975805  58.050474  
2007-09-03  16.925571  58.154835  
2007-09-04  16.919413  58.177640  
2007-09-05  17.017692  58.195446  
2007-09-06  16.975485  58.224743  

[5 rows x 30 columns]

In [98]:
#Import Global index data
idx_data = pd.read_csv('indices.csv', skiprows=1, parse_dates=['Date']).set_index(['Date'])
idx_data.head()

Hang Seng Index  SSE Composite Index  ASX All Ordinaries  \
Date                                                                   
2007-08-31         23984.14             5218.825              6248.3   
2007-09-03         23904.09             5321.055              6272.5   
2007-09-04         23886.07             5294.045              6297.1   
2007-09-05         24069.17             5310.716              6274.3   
2007-09-06         24050.40             5393.660              6265.3   

            India S&P BSE SENSEX    TOPIX  KOSPI Composite Index  \
Date                                                               
2007-08-31              15318.60  1608.25                1873.24   
2007-09-03              15422.05  1605.44                1881.81   
2007-09-04              15465.40  1596.74                1874.74   
2007-09-05              15446.15  1569.47                1865.59   
2007-09-06              15616.31  1568.52                1888.81   

            Taiwan TAIEX  FTSE Bursa Malaysia KLCI  FTSE Straits Times Index  \
Date                                                                           
2007-08-31       8982.16                   1273.93                   3328.43   
2007-09-03       8979.96                   1284.14                   3321.36   
2007-09-04       8922.98                   1283.75                   3308.81   
2007-09-05       8913.85                   1297.93                   3375.02   
2007-09-06       9017.08                   1298.85                   3399.49   

            Philippines PSE PSEi         ...          Turkey BIST 100  \
Date                                     ...                            
2007-08-31               3365.29         ...                 50198.60   
2007-09-03               3369.14         ...                 49936.94   
2007-09-04               3312.30         ...                 50032.59   
2007-09-05               3342.35         ...                 49421.38   
2007-09-06               3326.53         ...                 49601.39   

            S&P 500  DJ Industrial Average  Colombia IGBC  \
Date                                                        
2007-08-31  1473.99               13357.74       10728.74   
2007-09-03  1473.99               13357.74       10750.79   
2007-09-04  1489.42               13448.86       10880.85   
2007-09-05  1472.29               13305.47       10819.91   
2007-09-06  1478.55               13363.35       10844.40   

            Canada S&P/TSX Composite  Brazil Bovespa Index  Mexico IPC  \
Date                                                                     
2007-08-31                  13660.48              54637.24    30347.86   
2007-09-03                  13660.48              54832.51    30797.60   
2007-09-04                  13755.23              55250.47    30932.71   
2007-09-05                  13683.28              54407.83    30809.55   
2007-09-06                  13795.69              54569.00    30816.95   

            Israel TA-125  Saudi Arabia All Share (TASI)  FTSE JSE All Share  
Date                                                                          
2007-08-31        1034.67                        8226.97            28660.35  
2007-09-03        1047.33                        8017.54            28887.48  
2007-09-04        1054.69                        7878.70            29051.96  
2007-09-05        1048.70                        7853.66            28696.67  
2007-09-06        1033.23                        7853.66            28850.19  

[5 rows x 42 columns]

## Step 2: Pre-process Raw Data
1. Generate labels
2. Apply lags to global index data
3. Normalize features

In [99]:
#Generate Labels from Price History Data
#Generate UP/DOWN labels from log change
cutoff_perc = 0.0005 #0.05% return as cuttoff to define UP label
lag = 1 #forward returns

labels = np.zeros([price_hist_data.shape[0]])

#Caluclate log-returns
ret = np.log(price_hist_data['P'].shift(-lag)/price_hist_data['P'])
labels = [1 if r > cutoff_perc else 0 for r in ret]

In [100]:
#Applying lags to index data
#Seperate the indices into 2 classes - lag or no_lag
no_lag = [0, 1, 2, 4, 5, 6, 9, 10]
lag = [i for i in range(0,idx_data.shape[1]) if i not in no_lag]

#Processing the dataset by applying appropriate lags
lagged_data = idx_data.iloc[:,lag].shift(1)
idx_data = pd.concat([idx_data.iloc[:,no_lag], lagged_data], axis=1)


In [101]:
#Remove first row
idx_data = idx_data.iloc[1:, :]
price_hist_data = price_hist_data.iloc[1:, :]
fund_data = fund_data.iloc[1:, :]
labels=labels[1:]

In [103]:
#Check Dimensions to make sure everythings right before continuing..
print("Shape of idx_data: ", idx_data.shape)
print("Shape of price_hist_data: ", price_hist_data.shape)
print("Shape of fund_data: ", fund_data.shape)
print("Shape of labels: ", len(labels))

Shape of idx_data:  (2483, 42)
Shape of price_hist_data:  (2483, 21)
Shape of fund_data:  (2483, 30)
Shape of labels:  2483


In [104]:
#Training data
X = np.array(pd.concat([price_hist_data, idx_data, fund_data], axis=1))
y = to_categorical(labels, num_classes=2)

In [105]:
#Checking whether there are NAs
[np.sum(np.isnan(X), axis=0) > 0] == True

False

In [106]:
len(y.shape)


2

## Step 3: Split training, validation and test set

In this stage we have a look-ahead bias free set of data (X) and the labels y. Next, we will need to:
- Normalize the input data. To avoid look ahead bias, we will z-score the features, using ONLY the training set.
- Next, generate input data into LSTM network. We will need an overlapping sequence at 1-day window as input samples. Specifically suppose the *timestep* is 240, we will have a list of array consists of *number of rows of X* - 240 entries, each element has dimentions (240, num_of_features)


In [107]:
#Function to split raw data into training, validation and test set, returns a numpy array.
def split_data(input_data=[], train_size=0.8, val_size=0.2, test_size=0):
    
    #------------------------------------------------
    #PARAM: input_data: numpy nd array
    #PARAM: training_size: size of training set in decimal
    #PARAM: val_size: size of validation set in decimal
    #PARAM: test_size: size of test set in decimal
    #OUTPUT: tuple (train_set, validation_set, test_set)
    #------------------------------------------------
    
    #First check whether traing_size + val_size + test_size = 1 and each of the entries are positive
    assert(train_size + val_size + test_size==1), "Sum of training, validation and test size needs to be 1!"
    assert(train_size * val_size * test_size > 0), "Sizes have to be positive!"
    
    #Check input_data type is numpy array, after casting
    if type(input_data) != 'numpy.ndarray':
        input_data = np.array(input_data) 
    
    assert(isinstance(input_data, np.ndarray)), "Input has to be a numpy array!"
    
    
    #Calculate cut-off points
    train_cut_index = int(train_size * input_data.shape[0])
    val_cut_index = train_cut_index + int(val_size * input_data.shape[0])
    
    #Split the data
    if len(input_data.shape) == 1:
        train, val, test = input_data[:train_cut_index], input_data[train_cut_index:val_cut_index], input_data[val_cut_index:]
    else:
        train, val, test = input_data[:train_cut_index,:], input_data[train_cut_index:val_cut_index, :], input_data[val_cut_index:, :]
    
    return train, val, test

In [108]:
#------------
#TEST OUTPUT
#------------
#Split data
X_train, X_val, X_test = split_data(X, train_size=0.7, val_size=0.15, test_size=0.15)
y_train, y_val, y_test = split_data(y, train_size=0.7, val_size=0.15, test_size=0.15)
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)
print(y_train.shape)
print(y_val.shape)
print(y_test.shape)

(1738, 93)
(372, 93)
(373, 93)
(1738, 2)
(372, 2)
(373, 2)


In [109]:
#Function to re-structure the data to get batches. Re-shape the data to have overlapping training set for time-series learning.
def get_inputs(input_data, labels, timesteps):
    
    #First get the total number of samples generated
    n_seq = input_data.shape[0] - timesteps + 1
    
    #features, classes
    n_dim = input_data.shape[1]
    n_class = labels.shape[1]
    
    #Generate the sequences
    for ii in range(0, n_seq):        
        #Getting the overlapping samples
        yield np.reshape(scale(input_data[ii:ii+timesteps, :]), (-1, timesteps, n_dim)), np.reshape(labels[ii:ii+timesteps, :], (-1, timesteps, n_class))         


In [110]:
#------------
#TEST OUTPUT
#------------
#get inputs
t = np.reshape(np.arange(1,51), (10,5))
s = np.reshape(np.arange(1,21), (10,2))

g = get_inputs(t, s, 4)

for (x, y) in g:
    print('train:\n', x)
    print('labels:\n', y)
    

#print(test_train[0:1])
#print(test_label[0:1])
#print(t)
#print(test_train.shape)
#print(test_train)
#test_train.reshape((-1, 4, 5))

train:
 [[[-1.34164079 -1.34164079 -1.34164079 -1.34164079 -1.34164079]
  [-0.4472136  -0.4472136  -0.4472136  -0.4472136  -0.4472136 ]
  [ 0.4472136   0.4472136   0.4472136   0.4472136   0.4472136 ]
  [ 1.34164079  1.34164079  1.34164079  1.34164079  1.34164079]]]
labels:
 [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
train:
 [[[-1.34164079 -1.34164079 -1.34164079 -1.34164079 -1.34164079]
  [-0.4472136  -0.4472136  -0.4472136  -0.4472136  -0.4472136 ]
  [ 0.4472136   0.4472136   0.4472136   0.4472136   0.4472136 ]
  [ 1.34164079  1.34164079  1.34164079  1.34164079  1.34164079]]]
labels:
 [[[ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]]
train:
 [[[-1.34164079 -1.34164079 -1.34164079 -1.34164079 -1.34164079]
  [-0.4472136  -0.4472136  -0.4472136  -0.4472136  -0.4472136 ]
  [ 0.4472136   0.4472136   0.4472136   0.4472136   0.4472136 ]
  [ 1.34164079  1.34164079  1.34164079  1.34164079  1.34164079]]]
labels:
 [[[ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]
train:
 [[[-1.34164079 -1.34164079 -1.34164079 -1.3416407

/home/carnd/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/home/carnd/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/home/carnd/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/home/carnd/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/home/carnd/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversio

In [23]:
timesteps = 200
n_dim = X.shape[1]
n_classes = 2

#Normalize training data
X_train_np, y_train_np = get_inputs(X_train, y_train,timesteps)
X_val_np, y_val_np = get_inputs(X_val, y_val, timesteps)
X_test_np, y_test_np = get_inputs(X_test, y_test, timesteps)


ValueError: too many values to unpack (expected 2)

In [ ]:
print(len(X_train_np))
print(len(y_train_np))
print(len(X_val_np))
print(len(y_val_np))
print(len(X_test_np))
print(len(y_test_np))

In [ ]:
print(X_train_np.shape)
print(y_train_np.shape)

In [ ]:
new_train = np.reshape(X_train_np, (-1, timesteps, n_dim))
new_target = np.reshape(y_train_np, (-1, timesteps, n_classes))
new_val_X = np.reshape(X_val_np, (-1, timesteps, n_dim))
new_val_y = np.reshape(y_val_np, (-1, timesteps, n_classes))

## Train Model

In [111]:
#Define Parameters
learning_rate = 0.001
epochs= 5
loss = 'binary_crossentropy'
dropout=0.5

In [112]:
#Optimizer
optimizer = optimizers.Adam(lr=learning_rate)

In [129]:
#Model Architect
#-----------------

model = Sequential()

#Stack LSTM Cells
model.add(LSTM(100, input_shape=(timesteps, n_dim),  batch_size=1, return_sequences=True, stateful=True))

model.add(LSTM(50, return_sequences=True, stateful=True))

model.add(Dense(5, activation='relu'))

model.add(Dense(32, activation='relu'))

model.add(Dense(2, activation='sigmoid'))


model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_12 (LSTM)               (1, 200, 100)             77600     
_________________________________________________________________
lstm_13 (LSTM)               (1, 200, 50)              30200     
_________________________________________________________________
dense_11 (Dense)             (1, 200, 5)               255       
_________________________________________________________________
dense_12 (Dense)             (1, 200, 32)              192       
_________________________________________________________________
dense_13 (Dense)             (1, 200, 2)               66        
Total params: 108,313
Trainable params: 108,313
Non-trainable params: 0
_________________________________________________________________


In [130]:
#Compile
model.compile(loss=loss, optimizer=optimizer, metrics=['accuracy'])

In [132]:
#Fit
#fitted = model.fit(new_train, new_target, epochs=epochs, 
#                    validation_data=(new_val_X, new_val_y), 
#                    batch_size=1, verbose=1, shuffle=False)

for e in range(epochs):
    print("Epoch %d" %e)

    model.fit_generator(get_inputs(X_train, y_train, timesteps), steps_per_epoch=1738, 
                        epochs=epochs, verbose=1, validation_data=get_inputs(X_val, y_val, timesteps), validation_steps=1)

Epoch 0
Epoch 1/5
 320/1738 [====>.........................] - ETA: 393s - loss: 0.4738 - acc: 0.7734

KeyboardInterrupt: 

In [128]:
model.evaluate_generator(get_inputs(X_test, y_test, timesteps), 1)
model.predict_generator(get_inputs(X_test, y_test, timesteps), 1)


array([[[ 0.28595173,  0.74234563],
        [ 0.28251311,  0.74071151],
        [ 0.29610038,  0.70995146],
        [ 0.30838245,  0.6872794 ],
        [ 0.31741178,  0.68384141],
        [ 0.32216692,  0.69312745],
        [ 0.32994309,  0.69705737],
        [ 0.34048903,  0.69492328],
        [ 0.36727411,  0.66620725],
        [ 0.39751002,  0.6268782 ],
        [ 0.42251664,  0.59555292],
        [ 0.45492226,  0.5417155 ],
        [ 0.48006403,  0.49418449],
        [ 0.48994038,  0.47830442],
        [ 0.48516458,  0.4945263 ],
        [ 0.48720092,  0.48915905],
        [ 0.47690541,  0.50805002],
        [ 0.4784357 ,  0.50430465],
        [ 0.46653146,  0.53066087],
        [ 0.44723666,  0.5683319 ],
        [ 0.43100211,  0.59652102],
        [ 0.4144457 ,  0.62161201],
        [ 0.40455237,  0.63727212],
        [ 0.38703465,  0.66607821],
        [ 0.36195326,  0.70524049],
        [ 0.33536267,  0.74274641],
        [ 0.31111071,  0.77377915],
        [ 0.28680193,  0.800

# Below this line are old codes

In [ ]:
#Split into training, val and test set
#Parameters
train_size = 0.9
val_size = ( 1- train_size) * 0.5
timestep = 5

In [ ]:
#Calculate cutoff index values
train_cut_index = int(train_size * X.shape[0] - train_size * X.shape[0] % timestep)
val_cut_index = train_cut_index + int(val_size * X.shape[0] - val_size * X.shape[0] % timestep)
last_test_index = int(X.shape[0] - X.shape[0] % timestep)
print(train_cut_index)
print(val_cut_index)
print(last_test_index)

In [ ]:
#Spit Training, Validation and Test
X_train = np.array(X[0:train_cut_index,:])
X_val = np.array(X[train_cut_index:val_cut_index,:])
X_test = np.array(X[val_cut_index:last_test_index,:])

y_train = y[0:(train_cut_index)]
y_val = y[train_cut_index:val_cut_index]
y_test = y[val_cut_index:last_test_index]

print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

print(y_train.shape)
print(y_val.shape)
print(y_test.shape)

In [ ]:
#Preproc the y_train and y_test using to_categorical function
y_train = to_categorical(y_train, num_classes=2)
y_val = to_categorical(y_val, num_classes=2)
y_test = to_categorical(y_test, num_classes=2)

In [ ]:
#Reshape data for inputting into LSTM
X_train = np.reshape(X_train, (int(X_train.shape[0]/timestep), timestep, X_train.shape[1]))
X_val = np.reshape(X_val, (int(X_val.shape[0]/timestep), timestep, X_val.shape[1]))
X_test = np.reshape(X_test, (int(X_test.shape[0]/timestep), timestep, X_test.shape[1]))

y_train = np.reshape(y_train, (int(y_train.shape[0]/timestep), timestep, 2))
y_val = np.reshape(y_val, (int(y_val.shape[0]/timestep), timestep, 2))
y_test = np.reshape(y_test, (int(y_test.shape[0]/timestep), timestep, 2))

In [ ]:
X.iloc[0]

In [ ]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

print(y_train.shape)
print(y_val.shape)
print(y_test.shape)

In [ ]:
#y_train

## Step 4: Fit model


In [ ]:
#Import Library
from keras.layers import Activation, Dense, LSTM, Dropout

In [ ]:
#Define Parameters
learning_rate = 0.001
epochs= 100
loss = 'categorical_crossentropy'
dropout=0.5

In [ ]:
#Optimizer
optimizer = optimizers.Adam(lr=learning_rate)

In [ ]:
#Model Architect
#-----------------

model = Sequential()

#Stack LSTM Cells
model.add(LSTM(100, input_shape=X_train.shape[1:], batch_size=1, return_sequences=True, stateful=True))

model.add(LSTM(50, batch_size=1, return_sequences=True, stateful=True))

model.add(Dense(64, activation='relu'))

model.add(Dense(32, activation='relu'))

model.add(Dense(2, activation='softmax'))


model.summary()

In [ ]:
#Compile
model.compile(loss=loss, optimizer=optimizer, metrics=['accuracy'])

In [ ]:
#Fit
fitted = model.fit(X_train, y_train, epochs=epochs, validation_data=(X_val, y_val), batch_size=1, verbose=1, shuffle=False)

## Step 5: Evaluate


In [ ]:
### Plot Training vs Validation Curve
plt.figure()
plt.plot(fitted.history['loss'])
plt.plot(fitted.history['val_loss'])
plt.title('Training Loss & Validation Loss')
plt.ylabel('Binary Cross Entropy Loss')
plt.xlabel('Epoch')
plt.legend(['Training Loss', 'Validation Loss'])
plt.show()

In [ ]:
### Plot Training vs Validation Accuracy
plt.figure()
plt.plot(fitted.history['acc'])
plt.plot(fitted.history['val_acc'])
plt.title('Training Accuracy & Validation Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Training Accuracy', 'Validation Accuracy'])
plt.show()